import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body>
      <div className="fixed top-0 left-0 p-4">
        <Link href="/" className="text-blue-500 hover:underline text-2xl">
            ← Home
        </Link>
      </div>
      {children}
    </body>
  </html>
  );
}
